# Generated by Django 2.0.6 on 2018-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180629_0048'),
        ('members', '0002_auto_20180626_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='posts.Post'),
        ),
    ]
