# Generated by Django 2.0.6 on 2018-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180629_0048'),
        ('members', '0006_auto_20180629_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='to_relation_users',
            field=models.ManyToManyField(blank=True, related_name='from_relation_users', related_query_name='from_relation_user', to='posts.Post'),
        ),
    ]
